### ISSUE TITLE
Confused about oauth version (?)

### ISSUE THREAD

**Issue by averyfreeman** [HunterLarco/twitter-v2#12]
Hi again,

If I log a new Twitter object, I notice it says it's using Oauth 1.0

Isn't the app auth w/ bearer token oauth v2.0?  Reference: https://developer.twitter.com/en/docs/authentication/oauth-2-0  

This: 

```
import * as Twitter from 'twitter-v2';
import { apiKey, apiSecretKey, bearerToken } from 'keys';

const client = new Twitter({
  consumer_key: apiKey,
  consumer_secret: apiSecretKey,
  bearer_token: bearerToken,
});

console.log(client);
```

Returns this: 
```
Twitter {
  credentials: Credentials {
    _consumer_key: '...',
    _consumer_secret: '...',
    _bearer_token: '...',
    _access_token: undefined,
    _access_token_secret: undefined,
    _bearer_token_promise: null,
    _oauth: OAuth {
      consumer: [Object],
      nonce_length: 32,
      version: '1.0',
      parameter_seperator: ', ',
      realm: undefined,
      last_ampersand: true,
      signature_method: 'HMAC-SHA1',
      hash_function: [Function: hash_function],
      body_hash_function: [Function: hash_function]
    }
  }
}

```

FWIW, I'm GETting tweets just fine. Is the stated oauth version anything I should be concerned about?

Thanks

**Comment by HunterLarco** [comment]
As per the twitter documentation

> As this method [OAuth 2.0] is specific to the App, it does not involve any users. This method is typically for developers that need read-only access to public information. 

Right now this library uses OAuth 1.0 for both application and user authentication as it covers both use cases (resulting in less to maintain) however any contributions that would switch over to OAuth 2.0 only for application authentication would be welcome!

In the meantime I don't believe there's anything to be concerned about, OAuth 1.0 is stable for app authentication.
