### ISSUE TITLE
List of urlParams ?

### ISSUE THREAD

**Issue by averyfreeman** [HunterLarco/twitter-v2#13]
Hello, 

where might I find a list of the urlParams mentioned in the docs?

e.g.:
```
client.get(path, urlParams);
```

Thank you

**Comment by CiriousJoker** [comment]
Usually, Twitter responds with an error and a list of valid params.

I created the request using postman first: https://documenter.getpostman.com/view/9956214/T1LMiT5U

However, while this url is a valid request:
https://api.twitter.com/2/tweets/TWEET_ID?tweet.fields=author_id,conversation_id,referenced_tweets

both of these arent:

```
const data = client.get("tweets/TWEET_ID", {
  "tweet.fields": " author_id,conversation_id,referenced_tweets",
});
```

```
const data = client.get("tweets", {
  ids: "TWEET_ID",
  "tweet.fields": " author_id,conversation_id,referenced_tweets",
});
```

**Comment by HunterLarco** [comment]
The url params used by the client methods `get`, `post`, and `stream` all are the same as those used directly by Twitter (see [examples/get_tweets.js](https://github.com/HunterLarco/twitter-v2/blob/master/examples/get_tweets.js) for an example) they can be encoded two ways:

```js
{
  'foo.bar': 100,
  baz: 200,
}
```

would result in `?foo.bar=100&baz=200`

while so would the following:

```js
{
  foo: { bar: 100 },
  baz: 200,
}
```
