### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by PaulieScanlon** [HunterLarco/twitter-v2#17]
Hey, i just tried this out and it works a treat! Great job

I was wondering if i could help out at all?

There were one or two things i had to dig around the api docs for which might benefit from some extra code snippet examples in the README

For example i'm trying to get the last 100 tweets for my username and it took me a while to work out how to pass the params

```javascript
  const { data } = await client.get('tweets/search/recent', {
    query: 'PaulieScanlon',
    max_results: '100',
    tweet: {
      fields:
    'author_id,context_annotations,conversation_id,created_at,entities,geo,id,in_reply_to_user_id,lang,possibly_sensitive,public_metrics,referenced_tweets,source,text,withheld',
    },
  })
```

**Comment by HunterLarco** [comment]
Absolutely! The more help the merrier 👍 

Code examples and documentation are pretty minimal right now (which a few people have had questions about) most of the params are documented on twitter's website and this library serves as a convenient pass through. For example your above example can even be rewritten as:

```js
const { data } = await client.get('tweets/search/recent', {
  query: 'PaulieScanlon',
  max_results: '100',
  tweet: {
    fields: [
      'author_id',
      'context_annotations',
      'conversation_id',
      'created_at',
      'entities',
      'geo',
      'id',
      'in_reply_to_user_id',
      'lang',
      'possibly_sensitive',
      'public_metrics',
      'referenced_tweets',
      'source,text,withheld',
     ],
  },
})
```

If you have ideas on how to improve the documentation and/or underlying code, please consider submitting a PR and I'll happily take a look.
