### ISSUE TITLE
TypeScript definitions

### ISSUE THREAD

**Issue by brandongregoryscott** [HunterLarco/twitter-v2#21]
Are there any plans for writing TypeScript definitions for this package? I was planning on writing a wrapper library in TS to provide some utility functions around these base API calls and I've found myself filling in some of the types for this package anyway.

**Comment by HunterLarco** [comment]
Hey Brandon! Right now I don't have this on the roadmap, however a PR containing TypeScript definitions would be very appreciated. It sounds like you have something put together already. Let's get that merged in.

**Comment by brandongregoryscott** [comment]
👍 Awesome. Still a work in progress but I'll work on filling them out and open up a PR when I think it's ready.

**Comment by creativecreatorormaybenot** [comment]
That would definitely be much appreciated given how much it is used and how working without definitions is less than ideal :)
