### ISSUE TITLE
The "errors" field is a legitimate field returned by Twitter v2 - should not result in error thrown

### ISSUE THREAD

**Issue by chaodoze** [HunterLarco/twitter-v2#26]
In Twitter V2, the errors field of what's returned by Twitter is a legitimate field.

e.g. When we are looking up a tweet id that has been suspended, we would look in the errors field for this case.

Thus, it should not result in an error thrown, instead just return the errors field results

e.g. This tweet is from an account that is suspended, so 
client.get('tweets', {ids:'1000082502030065665'})
is a valid api call

It should return:
{"errors":[{"value":"1000082502030065665","parameter":"ids","resource_type":"tweet","section":"data","title":"Authorization Error","detail":"Sorry, you are not authorized to see the Tweet with ids: [1000082502030065665].","type":"https://api.twitter.com/2/problems/not-authorized-for-resource"}]}

**Comment by HunterLarco** [comment]
This issue is now fixed and released under v0.2.0
