### ISSUE TITLE
Twitter returned invalid request with parameters

### ISSUE THREAD

**Issue by danielchim** [HunterLarco/twitter-v2#31]
When trying to apply url parameters to links that have :parameters, it will return 'One or more parameters to your request was invalid.'

The problem code
```
const {data} = client.get('users/by/username/:username',{username :'INSERT NAME HERE'});
```
It will return the error I mentioned above.

**Comment by mafischer** [comment]
@danielchim I was thinking along the same lines as yourself, but was able to get it to work like this:

```javascript
const id = '1234567890';
const { data } = await client.get(`users/${id}/tweets`, { 
    max_results: 5,
    start_time: "2021-01-15T05:40:42Z",
    exclude: "retweets,replies"
});
console.log(data);
```

seems like the object you pass in is only intended for query params.

**Comment by HunterLarco** [comment]
@danielchim @mafischer that's correct:

> seems like the object you pass in is only intended for query params.

any path arguments should be constructed yourself with string interpolation.

**Comment by mafischer** [comment]
Would be nice to clarify this a bit in the docs, but hopefully at least this thread may help someone out in the future.
