### ISSUE TITLE
Stream Connection Problems

### ISSUE THREAD

**Issue by samudebug** [HunterLarco/twitter-v2#40]
Hello, I'm using this library to create a back-end to an App I'm building for my portfolio, so I don't plan on releasing it on an App Store.

One thing that it does is that it listens to tweets of the accounts the user has added to the app.

Since I'm still building it, I oftenly have to change one or two lines of code in the back-end, then save and it starts running again. But I'm having this annoying problem, that whenever the app stops and starts running again after a short time, the stream doesn't start so it can't listen to tweets.

```
TwitterError: ConnectionException: This stream is currently at the maximum allowed connection limit.
    at Function.module.exports.fromJson (/home/samuel/stlk-api/node_modules/twitter-v2/src/TwitterError.js:29:12)
    at Stream.<anonymous> (/home/samuel/stlk-api/node_modules/twitter-v2/src/TwitterStream.js:60:40)
    at Stream.emit (node:events:379:20)
    at Stream.EventEmitter.emit (node:domain:470:12)
    at drain (/home/samuel/stlk-api/node_modules/through/index.js:36:16)
    at Stream.stream.queue.stream.push (/home/samuel/stlk-api/node_modules/through/index.js:45:5)
    at emit (/home/samuel/stlk-api/node_modules/split/index.js:37:14)
    at Stream.<anonymous> (/home/samuel/stlk-api/node_modules/split/index.js:60:7)
    at _end (/home/samuel/stlk-api/node_modules/through/index.js:65:9)
    at Stream.stream.end (/home/samuel/stlk-api/node_modules/through/index.js:74:5) {
  details: 'https://api.twitter.com/2/problems/streaming-connection'
}
```

I've tried to listen to the stop events, but to no success

```
process.on('SIGTERM', () => {
        console.info('SIGTERM signal received.');
        console.log('Closing http server.');
        twitterService.closeStream();
    });
    process.on ('SIGINT', () => {
        console.info('SIGINT signal received.');
        console.log('Closing http server.');
        twitterService.closeStream();
        process.exit(0);
    }); 
```

Is there anything I can do to fix or workaround this?

**Comment by zane-programs** [comment]
I can confirm that I am having the same issue. It seems to be due to ratelimiting on the part of Twitter. Has anyone else experienced this behavior?

**Comment by HunterLarco** [comment]
Unfortunately @zane-programs is correct. [Twitter rate limits all streams](https://developer.twitter.com/en/docs/labs/v1/filtered-stream/faq) such that if you're frequently connecting and reconnecting you'll run into a `ConnectionException`.

Note that:

> Each app is allowed one connected client at a time. You can attempt reconnecting up to 15 times per 15 minute period. You can make up to 450 rule changes per 15 minute period.

and

> To check connection limits response will return three headers: x-rate-limit-limit, x-rate-limit-remaining and x-rate-limit-reset headers. This is useful to understand how many times you can use the rule endpoint, and how many reconnections attempts are allowed for the streaming endpoint.

If your dev workflow requires several restarts within a 15min period you may want to consider streaming from Twitter with a different process which your binary connects to instead. EG: create a thin JS client that connects to twitter and proxies all streamed data. In fact, that might not be a bad thing to add to this repository as a utility if there's enough interest.

**Comment by zane-programs** [comment]
Interestingly, this quirk does not just occur after restarts. In fact, I just applied for a new Twitter Developer account on my Twitter alt account, and I ran into the stream disconnect issue on my very first use of the new keys.

I don't think this is on @HunterLarco though; it seems to be a quirk with Twitter's streaming API itself. Alas, I'll be polling Twitter for now instead.
