### ISSUE TITLE
Validation error if only bearer token is provided (consumer_key and consumer_secret required)

### ISSUE THREAD

**Issue by wiertz** [HunterLarco/twitter-v2#47]
Thanks a lot for this package, it seems to make my twitter life substantially easier! A small issue I stumbled upon: 

consumer_key and consumer_secret are required and if not present the validation function in Credentials.js throws an error. However, app auth and streaming work fine just with the bearer token – with the advantage that the token can be used elsewhere, e.g. to update rules. I commented the lines out and streaming works fine.

**Comment by HunterLarco** [comment]
Yup you're absolutely correct. As per the [Twitter App-only Documentation](https://developer.twitter.com/en/docs/authentication/oauth-2-0/application-only)

> You can do application-only authentication using your apps consumer API keys, or by using a Bearer Token.

I'll get started on a fix. Thanks for finding this!

**Comment by HunterLarco** [comment]
Done! Released under [1.0.5](https://www.npmjs.com/package/twitter-v2/v/1.0.5)
