### ISSUE TITLE
Handle connection timeouts in stream

### ISSUE THREAD

**Issue by wiertz** [HunterLarco/twitter-v2#48]
Hi (again), this is more of a feature request: I like the provision of stream data through an async iterator. It's clean and simple. But I am trying to implement a reconnection logic and there seems no way to know the status of the connection 'from the outside' as twitters 'ping' signals are not propagated by the iterator (or I am missing something). 

ImO it would be helpful to either
- propagate twitters 'connection alive' info to the user through the iterator (arguably making it slightly less elegant as the user then has to check the data) or
- handle disconnects within the TwitterStream class (e.g. throwing/rejecting if no signal was received for a certain amount of time, Twitter suggests 20 seconds).

Cheers,
Thilo

PS I am aware that this is a rather small project and my limited JS skills mean that I am unlikely of much help with the code. Just indicate if you think this won't be taken much further and I'll stop bugging you with issues.

**Comment by HunterLarco** [comment]
Stream disconnection has been improved as of [1.0.6](https://www.npmjs.com/package/twitter-v2/v/1.0.6)

See the new [README.md](https://github.com/HunterLarco/twitter-v2/blob/master/README.md#streaming-api) for details.

Thanks for the help =)
