### ISSUE TITLE
Stream Disconnects Too Soon - Increase Heartbeat Wait

### ISSUE THREAD

**Issue by cschwalm** [HunterLarco/twitter-v2#64]
### Prerequisites

- [ X] Put an X between the brackets on this line if you have done all of the
      following:
  - Checked that your issue isn't already filed: [open issues][open-issues]
  - Checked the [bug report guidelines][bug-report-guidelines]

### Description

Twitter streaming consistently disconnects at the 21 to 22 second mark depending on lag. It seems they have adjusted their heartbeat length to be slower. Please adjust the hardcoded amount to 30 seconds. There is a referenced open PR that allows for it to be adjustable.

See: https://github.com/HunterLarco/twitter-v2/pull/63

### Steps to Reproduce

1. Testing on AWS has shown repeated disconnects. Running it locally with breakpoints confirms the 20 second timer occurs too quickly causing the stream to think it is disconnected.

**Expected behavior:**

The stream to stay open. It is closing before it receives the heartbeat.

**Actual behavior:**

The stream closes too early.

**Reproduces how often:**

It depends on the time of day. It seems Twitter has extended their heartbeat length to exactly 20 seconds. Any lag causes a disconnect.

### Versions

v1.0.7

[open-issues]: https://github.com/hunterlarco/twitter-v2/issues
[bug-report-guidelines]: https://github.com/HunterLarco/twitter-v2/blob/master/CONTRIBUTING.md#reporting-bugs

**Comment by HunterLarco** [comment]
This has been addressed and is fixed in [version 1.0.8](https://www.npmjs.com/package/twitter-v2/v/1.0.8)
