### ISSUE TITLE
More streaming examples

### ISSUE THREAD

**Issue by Arnique** [HunterLarco/twitter-v2#82]
## Summary

Can you add an example on how to get streams using **urlParams**?

## Motivation

I'm stuck trying to get real time tweets from specific accounts. The streaming example is too simple to assist me.

## Describe alternatives you've considered

I read the official API docs and it didn't help

[open features]: https://github.com/HunterLarco/twitter-v2/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement
[feature request guidelines]: https://github.com/HunterLarco/twitter-v2/blob/master/CONTRIBUTING.md#suggesting-enhancements

**Comment by wiertz** [comment]
The example below illustrates how to use url parameters to modify the payload of tweets. See the official twitter docs for further information on fields, expansions and media fields. If you would like to create a filter, also see the official docs as creating, modifying and deleting filter rules happens independent from the stream itself. 

```
const Twitter = require('twitter-v2')

const endpointParameters = {
    'tweet.fields': [ 'author_id', 'conversation_id' ],
    'expansions': [ 'author_id', 'referenced_tweets.id' ],
    'media.fields': [ 'url' ]
}

const client = new Twitter({ bearer_token: process.env.TWITTER_BEARER_TOKEN })
const filteredStream = client.stream('tweets/search/stream', endpointParameters)
```

**Comment by Arnique** [comment]
> The example below illustrates how to use url parameters to modify the payload of tweets. See the official twitter docs for further information on fields, expansions and media fields. If you would like to create a filter, also see the official docs as creating, modifying and deleting filter rules happens independent from the stream itself.
> 
> ```
> const Twitter = require('twitter-v2')
> 
> const endpointParameters = {
>     'tweet.fields': [ 'author_id', 'conversation_id' ],
>     'expansions': [ 'author_id', 'referenced_tweets.id' ],
>     'media.fields': [ 'url' ]
> }
> 
> const client = new Twitter({ bearer_token: process.env.TWITTER_BEARER_TOKEN })
> const filteredStream = client.stream('tweets/search/stream', endpointParameters)
> ```

Thank you for responding.

Another question though: In the docs it says you have to add rules before making a request for filtered stream. e.g
```
{
  "add": [
    {"value": "cat has:images", "tag": "cats with images"}
  ]
}
```
How do we do that with with this method?

**Comment by Arnique** [comment]
Ok I figured it out. You first use the convenience methods to make the calls described by twitter docs e.g to add rules, then request the stream.

```
    // Define rule as per twitter docs
    const body = {
      "add": [
        {"value": "from:WhaleTrades", "tag": "from whale trades"}
      ]
    }

    // Add above rule
    const r = await client.post("tweets/search/stream/rules", body);
    console.log(r);

    // Define params
    const streamParams = {
      'tweet.fields': [ 'author_id', 'conversation_id' ],
      'expansions': [ 'author_id', 'referenced_tweets.id' ],
      'media.fields': [ 'url' ]
    }
    
   // Request stream
    const stream = client.stream("tweets/search/stream", streamParams);

    for await (const { data } of stream) {
      console.log(data);
    }
```
