### ISSUE TITLE
Lost in Documentation, how to get all tweets by user? 

### ISSUE THREAD

**Issue by tobiasgrossmann** [HunterLarco/twitter-v2#84]
Sorry, a bit lost in the documentation, how to get all tweets of a user by screen_name or ID? 

                let { data } = await twitterclient.get('tweets', { screen_name: 'twitterapiscreenname' }); 

Thanks

**Comment by brandongregoryscott** [comment]
See this endpoint: https://developer.twitter.com/en/docs/twitter-api/tweets/timelines/api-reference/get-users-id-tweets

I'm not sure the V2 API provides a 'by username' endpoint for tweets just yet - there is an endpoint you can provide a `username` to in the route to retrieve their user object to pass the id to the above one ☝️ https://developer.twitter.com/en/docs/twitter-api/users/lookup/api-reference/get-users-by-username-username

See this repl for an example: https://replit.com/@brandongscott/Twitter-V2-List-Tweets-by-Username

Not to spam my own library here, but I have built some functions on top of this one to ease consumer use. Check it out if you'd like (built in TypeScript w/ definitions included): https://github.com/brandongregoryscott/ts-twitter-provider#getting-started
