### ISSUE TITLE
Sample codes for client.post(path, body, urlParams);

### ISSUE THREAD

**Issue by ray-bun** [HunterLarco/twitter-v2#87]
Hi, is it possible to post twit with version 2? Could I get sample codes for this: client.post(path, body, urlParams);
?
I'm getting an error when trying to post. Maybe the endpoint is not yet available on version 2?

**Comment by brandongregoryscott** [comment]
I don't believe posting tweets is available yet: https://developer.twitter.com/en/docs/twitter-api/early-access

The `post` function was probably added for future use, or possibly to create or remove favorites: [POST favorites/create](https://developer.twitter.com/en/docs/twitter-api/v1/tweets/post-and-engage/api-reference/post-favorites-create), [POST favorites/destroy](https://developer.twitter.com/en/docs/twitter-api/v1/tweets/post-and-engage/api-reference/post-favorites-destroy)

**Comment by ray-bun** [comment]
Ok thank you
